/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int32_t add(int32_t a, int32_t b){

	int32_t res;
	__asm volatile("SVC #30");
	__asm  volatile("MOV %0,R0": "=r"(res) ::);
	return res;
}
int32_t sub(int32_t a, int32_t b){
	int32_t res;
	__asm volatile("SVC #32");
	__asm volatile ("MOV %0,R0": "=r"(res) ::);
	return res;

}
int32_t mul(int32_t a, int32_t b){
	int32_t res;
	__asm volatile("SVC #33");
	__asm  ("MOV %0,R0": "=r"(res) ::);
	return res;

}
int32_t div(int32_t a, int32_t b){
	int32_t res;
	__asm volatile("SVC #34");
	__asm volatile ("MOV %0,R0": "=r"(res) ::);
	return res;

}



int main(void)
{
    /* Loop forever */
    int32_t res;

    res = add(40, -90);
    printf("Add result = %ld\n",res);

    res = sub(25,150);
    printf("Sub result = %ld\n",res);

    res = mul(374,890);
    printf("mul result = %ld\n", res);

    res = div(67,-3);
    printf("div result = %ld\n",res);





	for(;;);
}
__attribute ((naked)) void SVC_Handler(){

	__asm volatile ("MRS R0, MSP");
	__asm volatile ("B SVC_Handler_c");


}


void SVC_Handler_c(uint32_t *pMSP_base_addr)
{

	int32_t arg0, arg1, res;
	printf(" svc_handler triggered \n");
	uint8_t *pc_add = (uint8_t*)pMSP_base_addr[6];
	pc_add -=2;
	uint8_t svs_number = *pc_add;
	printf("data %d", svs_number );

	arg0 = pMSP_base_addr[0];
	arg1 = pMSP_base_addr[1];
	switch(svs_number)
	{
	case 30:
		res = arg0 + arg1;
		break;
	case 32:
		res = arg0 - arg1;
		break;
	case 33:
		res=arg0 * arg1;
		break;
	case 34:
		res=arg0 / arg1;
		break;
	default:
	}
	pMSP_base_addr[0]=res;

	//pMSP_base_addr[0]=svs_number;


}


